version: '2.4'

services: 
    
    mysql: 
        image: mysql
        container_name: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: dompedro_as
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - 3306:3306
    
    mongo:
        image: mongo:4
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
            MONGO_INITDB_DATABASE: fiscal
        ports:
            - 27017:27017
